"""UserSetting model name edited

Revision ID: 1393b661bf0f
Revises: 05ee725db839
Create Date: 2022-07-26 15:31:53.919314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1393b661bf0f'
down_revision = '05ee725db839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting', sa.String(length=128), nullable=True),
    sa.Column('setting_name', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_setting_setting_name'), ['setting_name'], unique=False)

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index('ix_user_settings_settings_name')

    op.drop_table('user_settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('settings', sa.BLOB(), nullable=True),
    sa.Column('settings_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index('ix_user_settings_settings_name', ['settings_name'], unique=False)

    with op.batch_alter_table('user_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_setting_setting_name'))

    op.drop_table('user_setting')
    # ### end Alembic commands ###
