"""renaming hybrid methods in item

Revision ID: 362aba953b7e
Revises: 1393b661bf0f
Create Date: 2022-07-31 01:44:36.811732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362aba953b7e'
down_revision = '1393b661bf0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index('ix_category_name')
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=True)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_item__name')
        batch_op.create_index(batch_op.f('ix_item_name'), ['name'], unique=False)
        batch_op.drop_column('_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_name', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_item_name'))
        batch_op.create_index('ix_item__name', ['_name'], unique=False)
        batch_op.drop_column('name')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_name'))
        batch_op.create_index('ix_category_name', ['name'], unique=False)

    # ### end Alembic commands ###
