"""unique constraint on Category model edited

Revision ID: c82297679cb4
Revises: 362aba953b7e
Create Date: 2022-08-11 00:32:14.755785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82297679cb4'
down_revision = '362aba953b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index('ix_category_name')
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=False)
        batch_op.create_index('index_category_user', ['name', 'user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index('index_category_user')
        batch_op.drop_index(batch_op.f('ix_category_name'))
        batch_op.create_index('ix_category_name', ['name'], unique=False)

    # ### end Alembic commands ###
